Figure({
    'data': [{'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
              'mode': 'markers',
              'name': 'test',
              'text': [cuba],
              'type': 'scatter',
              'x': [0.0],
              'y': [2.5]},
             {'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
              'mode': 'markers',
              'name': 'test',
              'text': [cuba],
              'type': 'scatter',
              'x': [5.0],
              'y': [5.0]},
             {'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
              'mode': 'markers',
              'name': 'test',
              'text': [cuba],
              'type': 'scatter',
              'x': [0.0],
              'y': [7.5]}],
    'frames': [{'data': [{'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [0.0],
                          'y': [2.5]},
                         {'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [5.0],
                          'y': [5.0]},
                         {'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [0.0],
                          'y': [7.5]}],
                'name': 'Frame: 1'},
               {'data': [{'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [5.0],
                          'y': [2.5]},
                         {'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [10.0],
                          'y': [5.0]},
                         {'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [5.0],
                          'y': [7.5]}],
                'name': 'Frame: 2'},
               {'data': [{'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [10.0],
                          'y': [2.5]},
                         {'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [15.0],
                          'y': [5.0]},
                         {'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [10.0],
                          'y': [7.5]}],
                'name': 'Frame: 3'},
               {'data': [{'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [15.0],
                          'y': [2.5]},
                         {'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [20.0],
                          'y': [5.0]},
                         {'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [15.0],
                          'y': [7.5]}],
                'name': 'Frame: 4'},
               {'data': [{'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [20.0],
                          'y': [2.5]},
                         {'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [25.0],
                          'y': [5.0]},
                         {'marker': {'size': [200], 'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': 'test',
                          'text': [cuba],
                          'type': 'scatter',
                          'x': [20.0],
                          'y': [7.5]}],
                'name': 'Frame: 5'}],
    'layout': {'hovermode': 'closest',
               'sliders': [{'active': 0,
                            'currentvalue': {'font': {'size': 20}, 'prefix': 'year', 'visible': True, 'xanchor': 'right'},
                            'len': 0.9,
                            'pad': {'b': 10, 't': 50},
                            'steps': [{'args': [['test'], {'frame': {'duration':
                                                300, 'redraw': False}, 'mode':
                                                'immediate', 'transition':
                                                {'duration': 300}}],
                                       'label': 'Step: 1',
                                       'method': 'animate'},
                                      {'args': [['test'], {'frame': {'duration':
                                                300, 'redraw': False}, 'mode':
                                                'immediate', 'transition':
                                                {'duration': 300}}],
                                       'label': 'Step: 2',
                                       'method': 'animate'},
                                      {'args': [['test'], {'frame': {'duration':
                                                300, 'redraw': False}, 'mode':
                                                'immediate', 'transition':
                                                {'duration': 300}}],
                                       'label': 'Step: 3',
                                       'method': 'animate'},
                                      {'args': [['test'], {'frame': {'duration':
                                                300, 'redraw': False}, 'mode':
                                                'immediate', 'transition':
                                                {'duration': 300}}],
                                       'label': 'Step: 4',
                                       'method': 'animate'},
                                      {'args': [['test'], {'frame': {'duration':
                                                300, 'redraw': False}, 'mode':
                                                'immediate', 'transition':
                                                {'duration': 300}}],
                                       'label': 'Step: 5',
                                       'method': 'animate'}],
                            'transition': {'duration': 300, 'easing': 'cubic-in-out'},
                            'x': 0.1,
                            'xanchor': 'left',
                            'y': 0,
                            'yanchor': 'top'}],
               'template': '...',
               'updatemenus': [{'buttons': [{'args': [None, {'frame': {'duration':
                                                      500, 'redraw': False},
                                                      'fromcurrent': True,
                                                      'transition': {'duration':
                                                      300, 'easing': 'quadratic-in-
                                                      out'}}],
                                             'label': 'Play',
                                             'method': 'animate'},
                                            {'args': [[None], {'frame':
                                                      {'duration': 0, 'redraw':
                                                      False}, 'mode': 'immediate',
                                                      'transition': {'duration':
                                                      0}}],
                                             'label': 'Pause',
                                             'method': 'animate'}],
                                'direction': 'left',
                                'pad': {'r': 10, 't': 87},
                                'showactive': False,
                                'type': 'buttons',
                                'x': 0.1,
                                'xanchor': 'right',
                                'y': 0,
                                'yanchor': 'top'}],
               'xaxis': {'range': [0, 85], 'title': {'text': 'Life Expectancy'}},
               'yaxis': {'title': {'text': 'GDP per Capita'}, 'type': 'log'}}
})