Figure({
    'data': [{'marker': {'sizemode': 'area', 'sizeref': 200000},
              'mode': 'markers',
              'name': '0',
              'text': [0],
              'type': 'scatter3d',
              'x': [5.0],
              'y': [5.0],
              'z': [1.4]},
             {'marker': {'sizemode': 'area', 'sizeref': 200000},
              'mode': 'markers',
              'name': '1',
              'text': [1],
              'type': 'scatter3d',
              'x': [0.0],
              'y': [2.5],
              'z': [1.4]},
             {'marker': {'sizemode': 'area', 'sizeref': 200000},
              'mode': 'markers',
              'name': '2',
              'text': [2],
              'type': 'scatter3d',
              'x': [0.0],
              'y': [7.5],
              'z': [1.4]}],
    'frames': [{'data': [{'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [0.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [0.0],
                          'y': [7.5],
                          'z': [1.4]}],
                'name': '0'},
               {'data': [{'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [10.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [7.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [0.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [0.0],
                          'y': [7.5],
                          'z': [1.4]}],
                'name': '1'},
               {'data': [{'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [15.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [10.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [10.0],
                          'y': [7.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [10.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [7.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [0.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [0.0],
                          'y': [7.5],
                          'z': [1.4]}],
                'name': '2'},
               {'data': [{'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [20.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [15.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [15.0],
                          'y': [7.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [15.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [10.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [10.0],
                          'y': [7.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [10.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [7.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [0.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [0.0],
                          'y': [7.5],
                          'z': [1.4]}],
                'name': '3'},
               {'data': [{'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [25.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [20.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [20.0],
                          'y': [7.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [20.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [15.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [15.0],
                          'y': [7.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [15.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [10.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [10.0],
                          'y': [7.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [10.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [7.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '0',
                          'text': [0],
                          'type': 'scatter3d',
                          'x': [5.0],
                          'y': [5.0],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '1',
                          'text': [1],
                          'type': 'scatter3d',
                          'x': [0.0],
                          'y': [2.5],
                          'z': [1.4]},
                         {'marker': {'sizemode': 'area', 'sizeref': 200000},
                          'mode': 'markers',
                          'name': '2',
                          'text': [2],
                          'type': 'scatter3d',
                          'x': [0.0],
                          'y': [7.5],
                          'z': [1.4]}],
                'name': '4'}],
    'layout': {'hovermode': 'closest',
               'sliders': [{'active': 0,
                            'currentvalue': {'font': {'size': 20}, 'prefix': 'Year:', 'visible': True, 'xanchor': 'right'},
                            'len': 0.9,
                            'pad': {'b': 10, 't': 50},
                            'steps': [{'args': [['0'], {'frame': {'duration': 300,
                                                'redraw': True}, 'mode':
                                                'immediate', 'transition':
                                                {'duration': 300}}],
                                       'label': '0',
                                       'method': 'animate'},
                                      {'args': [['1'], {'frame': {'duration': 300,
                                                'redraw': True}, 'mode':
                                                'immediate', 'transition':
                                                {'duration': 300}}],
                                       'label': '1',
                                       'method': 'animate'},
                                      {'args': [['2'], {'frame': {'duration': 300,
                                                'redraw': True}, 'mode':
                                                'immediate', 'transition':
                                                {'duration': 300}}],
                                       'label': '2',
                                       'method': 'animate'},
                                      {'args': [['3'], {'frame': {'duration': 300,
                                                'redraw': True}, 'mode':
                                                'immediate', 'transition':
                                                {'duration': 300}}],
                                       'label': '3',
                                       'method': 'animate'},
                                      {'args': [['4'], {'frame': {'duration': 300,
                                                'redraw': True}, 'mode':
                                                'immediate', 'transition':
                                                {'duration': 300}}],
                                       'label': '4',
                                       'method': 'animate'}],
                            'transition': {'duration': 300, 'easing': 'cubic-in-out'},
                            'x': 0.1,
                            'xanchor': 'left',
                            'y': 0,
                            'yanchor': 'top'}],
               'template': '...',
               'updatemenus': [{'buttons': [{'args': [None, {'frame': {'duration':
                                                      500, 'redraw': True},
                                                      'fromcurrent': True,
                                                      'transition': {'duration':
                                                      300, 'easing': 'quadratic-in-
                                                      out'}}],
                                             'label': 'Play',
                                             'method': 'animate'},
                                            {'args': [[None], {'frame':
                                                      {'duration': 0, 'redraw':
                                                      True}, 'mode': 'immediate',
                                                      'transition': {'duration':
                                                      0}}],
                                             'label': 'Pause',
                                             'method': 'animate'}],
                                'direction': 'left',
                                'pad': {'r': 10, 't': 87},
                                'showactive': False,
                                'type': 'buttons',
                                'x': 0.1,
                                'xanchor': 'right',
                                'y': 0,
                                'yanchor': 'top'}],
               'xaxis': {'range': [0, 85], 'title': {'text': 'xAxis'}},
               'yaxis': {'title': {'text': 'yAxis'}}}
})